#!/usr/bin/env bash
set -euo pipefail

# =============================================================================
# RDMA Setup Script for aws-c-s3-kiran
# 
# This script performs one-time setup:
#   1. Creates env_rdma.sh from template (if not exists)
#   2. Bootstraps CRT dependencies
#   3. Builds aws-c-s3 and the RDMA plugin
#
# Usage: ./scripts/setup_rdma.sh
# =============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

echo "=========================================="
echo "RDMA Setup for aws-c-s3-kiran"
echo "=========================================="
echo ""

# -----------------------------------------------------------------------------
# Step 1: Create env_rdma.sh if it doesn't exist
# -----------------------------------------------------------------------------

ENV_FILE="$SCRIPT_DIR/env_rdma.sh"

if [ ! -f "$ENV_FILE" ]; then
    echo "[setup] Creating env_rdma.sh..."
    
    cat > "$ENV_FILE" << 'ENVEOF'
#!/usr/bin/env bash
# Environment configuration for RDMA tests
# Auto-generated by setup_rdma.sh

# =============================================================================
# Repository Configuration
# =============================================================================

if [ -z "${REPO_ROOT:-}" ]; then
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    export REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
fi

# =============================================================================
# cuObject Configuration (RDMA support)
# =============================================================================

export CUOBJECT_ROOT_DIR=/home/lab/tim/nvme-direct/cuObject
export CUOBJECT_LIB_DIR="$CUOBJECT_ROOT_DIR/build/lib_src"
export CUFILE_LIB_DIR=/home/lab/tim/nvme-direct/lib/cufile
export CUFILE_RDMA_LIB_DIR=/home/lab/tim/nvme-direct/lib/mlx
export CUFILE_INCLUDE_DIR=/home/lab/tim/nvme-direct/cufile
export CUFILE_ENV_PATH_JSON="$CUOBJECT_ROOT_DIR/cuobj.json"

# =============================================================================
# Build Configuration
# =============================================================================

export PLUGIN_DIR="$REPO_ROOT/plugins/cuobject"
export PLUGIN_BUILD_DIR="$PLUGIN_DIR/build"
export CRT_PREFIX="$REPO_ROOT/local-install"

# =============================================================================
# AWS/MinIO Credentials
# =============================================================================

export AWS_ACCESS_KEY_ID=minioadmin
export AWS_SECRET_ACCESS_KEY=minioadmin
export AWS_REGION=us-east-1
export AWS_DEFAULT_REGION=us-east-1

# =============================================================================
# Test Endpoint Configuration
# =============================================================================

# MinIO S3 endpoint (RDMA server)
export CRT_S3_TEST_ENDPOINT="200.1.84.163:9000"
export CRT_S3_TEST_BUCKET_NAME="aws-c-s3-test-bucket"
export S3_HTTP_ENDPOINT="http://200.1.84.163:9000"

# cuObject server (RDMA data plane)
export CUOBJ_SERVER_ADDR=200.1.84.163:17123

# Skip checksum validation (MinIO doesn't return checksums on GET)
export CRT_S3_TEST_SKIP_CKSUM_VALIDATE=1

# =============================================================================
# RDMA Runtime Configuration
# =============================================================================

if [ -n "${CUFILE_ENV_PATH_JSON:-}" ] && [ -f "$CUFILE_ENV_PATH_JSON" ]; then
    echo "[env_rdma] Using CUFILE_ENV_PATH_JSON=$CUFILE_ENV_PATH_JSON"
fi

export CMAKE_PREFIX_PATH="$CRT_PREFIX"
export PATH="$CRT_PREFIX/bin:$PATH"
export LD_LIBRARY_PATH="$CRT_PREFIX/lib:${LD_LIBRARY_PATH:-}"
export AWS_S3_RDMA_PLUGIN_PATH="$PLUGIN_BUILD_DIR/libcuobject_s3_plugin.so"
export AWS_S3_FORCE_RDMA=1
export AWS_S3_RDMA_THRESHOLD_BYTES="${AWS_S3_RDMA_THRESHOLD_BYTES:-1048576}"

# Set LD_PRELOAD for cuFile libraries
if [ -d "$CUFILE_LIB_DIR" ]; then
    CUFILE_LIB=$(find "$CUFILE_LIB_DIR" -maxdepth 1 -name "libcufile.so*" -type f 2>/dev/null | head -1)
    CUFILE_RDMA_LIB=""
    if [ -d "$CUFILE_RDMA_LIB_DIR" ]; then
        CUFILE_RDMA_LIB=$(find "$CUFILE_RDMA_LIB_DIR" -maxdepth 1 -name "libcufile_rdma.so*" -type f 2>/dev/null | head -1)
    fi
    if [ -n "$CUFILE_LIB" ] && [ -n "$CUFILE_RDMA_LIB" ]; then
        export LD_PRELOAD="$CUFILE_LIB $CUFILE_RDMA_LIB"
        echo "[env_rdma] LD_PRELOAD set for cuFile libraries"
    fi
fi

echo "[env_rdma] Environment configured:"
echo "[env_rdma]   REPO_ROOT: $REPO_ROOT"
echo "[env_rdma]   CRT_PREFIX: $CRT_PREFIX"
echo "[env_rdma]   CRT_S3_TEST_ENDPOINT: $CRT_S3_TEST_ENDPOINT"
echo "[env_rdma]   CUOBJ_SERVER_ADDR: $CUOBJ_SERVER_ADDR"
echo "[env_rdma]   RDMA Support: ENABLED"
ENVEOF

    chmod +x "$ENV_FILE"
    echo "[setup] Created $ENV_FILE"
else
    echo "[setup] env_rdma.sh already exists, skipping creation"
fi

# -----------------------------------------------------------------------------
# Step 2: Source environment
# -----------------------------------------------------------------------------

echo ""
echo "[setup] Loading environment..."
# shellcheck disable=SC1090
source "$ENV_FILE"

# -----------------------------------------------------------------------------
# Step 3: Bootstrap CRT dependencies (if needed)
# -----------------------------------------------------------------------------

if [ ! -d "$CRT_PREFIX/lib" ] || [ ! -f "$CRT_PREFIX/lib/libaws-c-common.a" ]; then
    echo ""
    echo "[setup] Bootstrapping CRT dependencies (this takes ~5 minutes)..."
    bash "$SCRIPT_DIR/bootstrap_crt.sh"
else
    echo ""
    echo "[setup] CRT dependencies already installed, skipping bootstrap"
fi

# -----------------------------------------------------------------------------
# Step 4: Build aws-c-s3 and plugin
# -----------------------------------------------------------------------------

echo ""
echo "[setup] Building aws-c-s3 and RDMA plugin..."
bash "$SCRIPT_DIR/build_all.sh" --skip-crt-check

# -----------------------------------------------------------------------------
# Step 5: Build tests
# -----------------------------------------------------------------------------

echo ""
echo "[setup] Building tests..."
cmake -S "$REPO_ROOT" -B "$REPO_ROOT/build" \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo \
    -DBUILD_TESTING=ON \
    -DCMAKE_PREFIX_PATH="$CRT_PREFIX" \
    -DCMAKE_INSTALL_PREFIX="$CRT_PREFIX" > /dev/null

cmake --build "$REPO_ROOT/build" -j > /dev/null

# -----------------------------------------------------------------------------
# Done
# -----------------------------------------------------------------------------

echo ""
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "To run tests:"
echo "  cd $REPO_ROOT"
echo "  source scripts/env_rdma.sh"
echo "  ctest --test-dir build -V -R 'test_s3_get_object_less_than_part_size'"
echo ""
echo "To verify RDMA is working:"
echo "  ./scripts/verify_rdma.sh"
echo ""

